language: java
install: ant templates
jdk:
  - oraclejdk9

before_install:
 - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.3-bin.tar.gz
 - tar -xzvf apache-ant-1.10.3-bin.tar.gz
 - export PATH=`pwd`/apache-ant-1.10.3/bin:$PATH
 - echo $(ant -version)